name: Build and Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.11
      with:
        # The name of the image you would like to push
        name: momoconsulting/githubactions:v7
        # The login username for the registry
        username: momoconsulting
        # The login password for the registry
        password: ${{ secrets.DOCKERHUB_PASS }}
        # Use registry for pushing to a custom registry
        #registry: # optional
        # Use snapshot to push an additional image
        #snapshot: # optional
        # Use dockerfile when you would like to explicitly build a Dockerfile
        #dockerfile: Dockerfile
        # Use workdir when you would like to change the directory for building
        #workdir: # optional
        # Use buildargs when you want to pass a list of environment variables as build-args
        #buildargs: # optional
        # Use cache when you have big images, that you would only like to build partially
        #cache: # optional
        # Use tag_names when you want to push tags/release by their git name
        #tag_names: $(date +%s)
    - name: AWS ECR
      uses: kciter/aws-ecr-action@v1
      with:
        # The AWS access key id
        access_key_id: XXXXXXXX
        # The AWS secret access key
        secret_access_key: XXXXXX
        # AWS Account ID
        account_id: XXXX
        # Name of your ECR repository
        repo: XXXX
        # The AWS region
        region: XXXX
        # Set this to true to create the repository if it does not already exist
        #create_repo: # optional
        # Comma-separated string of ECR image tags
        #tags: # optional, default is latest
        # Name of Dockerfile to use
        #dockerfile: # optional, default is Dockerfile
        # Extra flags to pass to docker build (see docs.docker.com/engine/reference/commandline/build)
        #extra_build_args: # optional, default is 
        # Path to Dockerfile, defaults to the working directory
        #path: # optional, default is .
